name: workflow-one
on: workflow_dispatch
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: |
          echo "Hello World!"
          echo "The world never greets back with a hello."
      - name: print closing
        run: echo "Closing step"
